### ISSUE TITLE
Server shutdown results in NullPointerException's being thrown (at com.caucho.util.ThreadPool$Item.access$200(ThreadPool.java:432)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Alfresco/alfresco-php-sdk#8]
```
When using community-2.1 with the phpIntegration AMP, a server shutdown results 
in

Sep 17, 2007 2:52:07 PM org.apache.catalina.core.StandardService stop
INFO: Stopping service Catalina
14:52:08,578 ERROR [openoffice.connection.SocketOpenOfficeConnection] 
disconnected unexpectedly
Sep 17, 2007 2:52:12 PM com.caucho.util.ThreadPool$Item runTasks
WARNING: java.lang.NullPointerException
java.lang.NullPointerException
        at com.caucho.util.Alarm.extractAlarm(Alarm.java:374)
        at com.caucho.util.Alarm$CoordinatorTask.run(Alarm.java:607)
        at com.caucho.util.ThreadPool$Item.runTasks(ThreadPool.java:600)
        at com.caucho.util.ThreadPool$Item.run(ThreadPool.java:522)
        at java.lang.Thread.run(Thread.java:613)
java.lang.NullPointerException
        at com.caucho.util.ThreadPool$Item.access$200(ThreadPool.java:432)
        at com.caucho.util.ThreadPool.schedule(ThreadPool.java:368)
        at com.caucho.util.ThreadPool.schedulePriority(ThreadPool.java:270)
        at com.caucho.util.Alarm$CoordinatorTask.schedule(Alarm.java:591)
        at com.caucho.util.Alarm$AlarmThread.run(Alarm.java:560)

The issue is documented in the forum, 

  http://forums.alfresco.com/viewtopic.php?p=28306&

in more detail and I just compiled a SVN build of Alfresco (revision) and the 
result is still the same. 

```

Original issue reported on code.google.com by `rwether...@gmail.com` on 25 Nov 2011 at 6:10

**Comment by ghost** [comment]
Repository no longer supported. Archiving repository and closing the tickets.
